config/routes.rb
Rails.application.routes.draw do
  resources :kanris, only: [:create, :destroy,:edit,:view,:index,:new]
  get  'tops/main'
  root 'tops#main'
  get 'tops/st_login'
  post 'tops/st_login'
  get 'tops/friend'
  post 'tops/friend'
  get  'tops/st_logout'
  get 'tops/ka_login'
  post 'tops/ka_login'
  get  'tops/ka_logout'
  post 'subjects/:id/edit' => 'subjects#edit'
  get 'students/search'
  post 'students/search'
    get 'students/itiran'
  post 'students/itiran'
  resources :subjects, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :students, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :items, only: [:index,:show,:new,:create,:destroy]
  resources :schedules, only: [:index,:show,:create]
  
end

app/models/student.rb
class Student < ActiveRecord::Base
   has_many :subjects
   has_many :schedules
  validates :st_id, presence: true, uniqueness: true
    validates :st_name, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true
  attr_accessor :password
    def password=(val)
    if val.present?
      self.st_pass = BCrypt::Password.create(val)
    end
     @password = val
    end
    
   def self.authenticate(st_id, st_pass)
    student = Student.find_by_st_id(st_id)
    if student && BCrypt::Password.new(student.st_pass) == st_pass
      student
    else
      nil
    end
   end
      scope :get_by_st_id, ->(st_id) {
where("st_id like ?" ,"%#{st_id}%")
}
   scope :get_by_st_name, ->(st_name) {
where("st_name like ?" ,"%#{st_name}%")
}
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
    
    if params[:st_id].present? 
    @students = @students.get_by_st_id params[:st_id]
    end  
    
    if params[:st_name].present? 
    @students = @students.get_by_st_name params[:st_name]
    end
  end

    
 def new
   @student = Student.new
 end
  
  def create
    @student = Student.new(
     st_id: params[:student][:st_id],
     st_name: params[:student][:st_name],
     password: params[:student][:password],
     password_confirmation: params[:student][:password_confirmation])
    if @student.save
      redirect_to tops_st_login_path
    else
      render 'new'
    end
  end

 def destroy
  Student.find(params[:id]).destroy
  session.delete(:st_login_uid)
    redirect_to tops_st_login_path
 end 
 def search
    @students = Student.all
    
    if params[:st_id].present? 
    @students = @students.get_by_st_id params[:st_id]
    end  
    
    if params[:st_name].present? 
    @students = @students.get_by_st_name params[:st_name]
    end
    
 end
 def itiran
    @students = Student.all
 end
 end

app/helpers/students_helper.rb
module StudentsHelper

end

app/views/students/index.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">友人を探す</font></p>
　　<%= link_to 'メインメニューへ', tops_main_path ,class: "btn btn-mini btn-danger"%>
  <hr color="back" >
</div>
  </head>
  <div> 
<%= form_tag(students_search_path, method: "get") do %>
<%= label_tag :st_id, "ID" %><%= text_field_tag :st_id, params[:st_id] %>
<%= label_tag :st_name, "名前" %><%= text_field_tag :st_name, params[:st_name] %>
<%= submit_tag "検索" %>
<% end %>
</div>

app/views/students/itiran.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">アカウントの削除</font></p>
　　<%= link_to 'メインメニューへ', tops_main_path ,class: "btn btn-mini btn-danger"%>
  <hr color="back" >
</div>
  </head>
<table border="1"class="ss">
	<tr>
		<th>ID</th>
		<th>ニックネーム</th>
		<th>パスワード</th>
		<th>操作</th>
	</tr>

<% @students.each do |e| %>
	<tr>
		<td><%= e.st_id%></td>
		<td><%= e.st_name %></td>
		<td><%= e.password %></td>
		<td>
		  <%if current_user.id == e.id %>
			<%= link_to '削除', student_path(e), method: :delete, data: { confirm: '削除していいですか？' } %>
		</td>
	</tr>
<% end %>
<% end %>
</table>

app/views/students/new.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">新規アカウント作成</font></p>
<%= link_to 'トップへ', root_path ,class: "btn btn-mini btn-danger"%>
<%= link_to 'ログイン画面に戻る', tops_st_login_path ,class: "btn btn-mini btn-danger"%>
  <hr color="back" >
</div>
  </head>
<% if @student.errors.present? %>
<h3>エラーがあります</h3>
<ul>
	<% @student.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
	<% end %>
</ul>
<% end %>


<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            
            <div class="account-wall">
            	<h1 class="text-center login-title">Create new account</h1>
            	<br>
                <div class="form-signin">
<%= form_for @student do |f| %>
	<tr>
		<td><%= f.label :st_id, 'ID' %></td>
		<td><%= f.text_field :st_id , class: 'form-control', autofocus: true %></td>
	</tr>
		<br>
	<tr>
		<td><%= f.label :st_name, 'ニックネーム' %></td>
		<td><%= f.text_field :st_name, class: 'form-control', autofocus: true %></td>
	</tr>
	<br>
	<tr>
			<td><%= f.label :password, 'パスワード' %></td>
		<td><%= f.password_field :password, class: 'form-control', autofocus: true %></td>
	</tr>
	<br>
		<tr>
		<td><%= f.label :password_confirmation, 'パスワード（確認）' %></td>
		<td><%= f.password_field :password_confirmation, class: 'form-control' , autofocus: true %></td>
	</tr>
	<br>
	<tr>
		<td colspan="2"><%= f.submit '登録',class:"btn btn-lg btn-primary btn-block" %></td>
	</tr>
<% end %>
                </label>
                <br>
                </form>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/students/search.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">検索結果</font></p>
　　<%= link_to 'トップメニューへ', tops_main_path ,class: "btn btn-mini btn-danger"%>
  <hr color="back" >
</div>
  </head>
<div> 
<%= form_tag(students_search_path, method: "get") do %>
<%= label_tag :st_id, "ID" %><%= text_field_tag :st_id, params[:st_id] %>
<%= label_tag :st_name, "名前" %><%= text_field_tag :st_name, params[:st_name] %>
<%= submit_tag "検索" %>
<% end %>
</div>
<table border="1" class="ss">
	<tr>
		<th>ID</th>
		<th>ニックネーム</th>
		<th>パスワード</th>
	</tr>

<% @students.each do |e| %>
	<tr>
		<td><%=link_to e.st_id,tops_friend_path%></td>
		<td><%= e.st_name %></td>
		<td><%= e.password %></td>
	</tr>
<% end %>


</table>