config/routes.rb
Rails.application.routes.draw do
  resources :kanris, only: [:create, :destroy,:edit,:view,:index,:new]
  get  'tops/main'
  root 'tops#main'
  get 'tops/st_login'
  post 'tops/st_login'
  get 'tops/friend'
  post 'tops/friend'
  get  'tops/st_logout'
  get 'tops/ka_login'
  post 'tops/ka_login'
  get  'tops/ka_logout'
  post 'subjects/:id/edit' => 'subjects#edit'
  get 'students/search'
  post 'students/search'
    get 'students/itiran'
  post 'students/itiran'
  resources :subjects, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :students, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :items, only: [:index,:show,:new,:create,:destroy]
  resources :schedules, only: [:index,:show,:create]
  
end

app/models/top.rb
class Top < ActiveRecord::Base
  # ユーザー名による絞り込み
scope :get_by_st_name, ->(st_name) {
where("name like ?", "%#{st_name}%")
}
# 性別による絞り込み
scope :get_by_st_id, ->(st_id) {
where("name like ?", "%#{st_id}%")
}
# パスワードによる絞り込み
scope :get_by_st_pass, ->(st_pass) {
where("name like ?", "%#{st_pass}%")
}
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
	if session[:st_login_uid] then
	    @students = Student.all
        @subjects = Subject.all
	    render 'next'
	     else if session[:ka_login_uid] then
	        @kanris = Kanri.all
	        @subject = Subject.all
	        render 'next2'
	    else
	        render 'main'
        end
        end
  end

 def st_login
		student = Student.authenticate(params[:st_id], params[:st_pass])
		if student
			session[:st_login_uid] = params[:st_id]
			redirect_to root_path
		else
			render 'tops/st_login_form'
		end
 end
 
  def friend
      student = Student.find_by(st_id: params[:st_id])
      if student && student.st_name == params[:st_name]
			session[:st_login_uid] = params[:st_id]
			redirect_to items_path
		else
			flash[:alert] = 'IDもしくは名前に誤りがあります'
			render 'tops/friend_form'
      end
  end

 def ka_login
		kanri = Kanri.authenticate(params[:ka_id], params[:ka_pass])
		if kanri
			session[:ka_login_uid] = params[:ka_id]
			redirect_to tops_main_path
		else
			flash[:alert] = 'IDもしくはパスワードに誤りがあります'
			render 'tops/ka_login_form'
		end
 end

	def st_logout
		session.delete(:st_login_uid)
		redirect_to tops_st_login_path
	end
	
	def ka_logout 
		session.delete(:ka_login_uid)
		redirect_to tops_ka_login_path
	end
	
def edit
  @subject = Subject.find(params[:id])
  render edit_subject_path
end

def update 
  @subject =Subject.find(params[:id])
  @subject = Subject.update(
    kamoku: params[:subject][:kamoku], 
    professor: params[:subject][:professor],
    unit: params[:subject][:unit],
    youbi: params[:subject][:youbi],
    zigen: params[:subject][:zigen])
  redirect_to subjects_path
end 
	
 def destroy
  Subject.find(params[:id]).destroy
  render 'next2'
 end 
 
 def search
  if params[:st_id].present?
  @students = @students.get_by_st_id　params[:st_id]
  end
  if params[:st_name].present?
  @students = @students.get_by_st_name params[:st_name]
  end
  if params[:st_pass].present?
  @students = @students.get_by_st_pass params[:st_pass]
  end
 end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/friend_form.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">フレンドログイン</font></p>
  　　	<%= link_to 'メインメニューへ', tops_st_login_path ,class: "btn btn-mini btn-danger"%>
  <hr color="back" >
</div>
  </head>
<% flash.each do |type, msg| %>
	<p style="color:red;">
		<%= msg %>
	</p>
<% end %>

<%= form_tag tops_friend_path do %>

<table>
	<tr>
		<td><%= label_tag :st_id, 'ID' %></td>
		<td><%= text_field_tag :st_id %></td>
	</tr>
<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><%= label_tag :st_name, '名前' %></td>
		<td><%= password_field_tag :st_name %></td>
	</tr>
<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		</tr>
		<tr>
		<td colspan="2"><%= submit_tag 'ログイン' %></td>
	</tr>
</table>

<% end %>

app/views/tops/ka_login_form.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">
<div class="header" %>
  <p><font size="7">管理者ログイン</font></p>


<%= link_to 'トップへ', root_path, class: "btn btn-mini btn-danger" %>
<%= link_to '管理ユーザ登録', new_kanri_path , class: "btn btn-mini btn-danger"%>

</div>
<hr >

<% flash.each do |type, msg| %>
	<p style="color:red;">
		<%= msg %>
	</p>
<% end %>

<%= form_tag tops_ka_login_path do %>

<table>
	<tr>
		<td><%= label_tag :ka_id, 'ID' %></td>
		<td><%= text_field_tag :ka_id %></td>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><%= label_tag :ka_pass, 'パスワード' %></td>
		<td><%= password_field_tag :ka_pass %></td>
	</tr>
	<tr>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td></td>
		<td colspan="2"><%= submit_tag 'ログイン' %></td>
	</tr>
	<tr>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td></td>

		</tr>
</table>

<% end %>

app/views/tops/main.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">時間割アプリ</font></p>
  <hr color="block" >
</div>
  </head>
<body>
  
<br>
<br><br>


<div class="place" %>
  <div class="container">
  <%= link_to '生徒用ログイン', tops_st_login_path,class: 'btn-push' %>
  <br><br><br><br>
  <%= link_to '教員用ログイン', tops_ka_login_path ,class: 'btn-push' %>
  </div>

</div>
</div>

</body>
</div>

app/views/tops/next.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">
 <div class="size">
 ようこそ<%= current_user.st_name %>さん[<%= link_to 'ログアウト', tops_st_logout_path %>]
 </div>
<%= form_tag tops_st_login_path do %>
<div class="header" %>
  <p><font size="7">メインメニュー</font></p>

</div>
<hr >
<input type="checkbox" id="cp_navimenuid">
<label class="menu" for="cp_navimenuid">

<div class="menubar">
	<span class="bar"></span>
	<span class="bar"></span>
	<span class="bar"></span>
</div>

<ul>
  
<li><%= link_to "友達検索 ",students_path ,class: 'btn btn-warning'%></li>
<li><%= link_to "時間割の表示", item_path(:show) ,class: 'btn btn-warning'%></li>
<li><%= link_to "時間割作成",new_item_path(:new) ,class: 'btn btn-warning'%></li>
<li><%= link_to "ユーザ削除",students_itiran_path,class: 'btn btn-warning' %></li>
</li>
</ul>

</label>
<% end %>

app/views/tops/next2.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

 <% @kanris.each do |f| %>
 <% if current_user2.ka_id == f.ka_id %>
 <div class="size">
 管理者<%= f.ka_id%>ログイン中[<%= link_to 'ログアウト', tops_ka_logout_path %>]
 </div>
<div class="header" %>
  <p><font size="7">登録済講義一覧</font></p>
  	<%= link_to 'ユーザ一覧', kanris_path,class: "btn btn-mini btn-danger"%>
  　<%= link_to '講義登録', new_subject_path ,class: "btn btn-mini btn-danger"%>
  <hr color="block" >
</div>
  <div class="s">
  <%= flash[:sakuzyo_kougi] %>
  <%= flash[:touroku_kougi] %>
  <%= flash[:syuusei_kougi] %>
  </div>
	<table border="1" class="ss">

	<tr>
		<th>科目</th>
		<th>教授名</th>
		<th>単位数</th>
		<th>曜日</th>
		<th>時限</th>
		<th>操作</th>
	</tr>
<% @subject.each do |e| %>

	<tr>
		<td><%= e.kamoku %></td>
		<td><%= e.professor %></td>
		<td><%= e.unit %></td>
		<td><%= e.youbi %></td>
		<td><%= e.zigen %></td>
		<td>
			<%= link_to '編集', edit_subject_path(e), method: :update, data: { confirm: '編集しますか？' } %>
			<%= link_to '削除', subject_path(e), method: :delete, data: { confirm: '削除していいですか？' } %>
		</td>
	</tr>
<% end %>
<% end %>
<% end %>
</table>

app/views/tops/st_login_form.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<% flash.each do |type, msg| %>
	<p style="color:red;">
		<%= msg %>
	</p>
<% end %>

<%= form_tag tops_st_login_path do %>
<div class="header" %>
  <p><font size="7">生徒ログイン</font></p>
　　<%= link_to 'トップへ', tops_main_path,class: "btn btn-mini btn-danger" %>　　
</div>
<hr >
<% end %>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
          
            <div class="account-wall">
            	<h1 class="text-center login-title">Sign in to continue to Timetable</h1>
            	<br>
                <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120" alt="">
                <form class="form-signin">
                <input type="text" name="st_id" class="form-control" placeholder="ID" required autofocus>
                <input type="password" name="st_pass" class="form-control" placeholder="Password" required>
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Sign in</button>
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    Remember me
                </label>
                <br>
                </form>
                <%= link_to 'Create an account', new_student_path,  { :class => "text-center new-account" } %>
            </div>
            
        </div>
    </div>
</div>