config/routes.rb
Rails.application.routes.draw do
  resources :kanris, only: [:create, :destroy,:edit,:view,:index,:new]
  get  'tops/main'
  root 'tops#main'
  get 'tops/st_login'
  post 'tops/st_login'
  get 'tops/friend'
  post 'tops/friend'
  get  'tops/st_logout'
  get 'tops/ka_login'
  post 'tops/ka_login'
  get  'tops/ka_logout'
  post 'subjects/:id/edit' => 'subjects#edit'
  get 'students/search'
  post 'students/search'
    get 'students/itiran'
  post 'students/itiran'
  resources :subjects, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :students, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :items, only: [:index,:show,:new,:create,:destroy]
  resources :schedules, only: [:index,:show,:create]
  
end

app/models/kanri.rb
class Kanri < ActiveRecord::Base
   has_many :subject
  validates :ka_id, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true
    attr_accessor :password
    def password=(val)
    if val.present?
    self.ka_pass = BCrypt::Password.create(val)
    end
     @password = val
    end
   
   def self.authenticate(ka_id, ka_pass)
    kanri = Kanri.find_by_ka_id(ka_id)
    if kanri && BCrypt::Password.new(kanri.ka_pass) == ka_pass
      kanri
    else
      nil
    end
   end
end

app/controllers/kanris_controller.rb
class KanrisController < ApplicationController
  def index 
    @kanris = Kanri.all
  end
    
  def new
   @kanri = Kanri.new
  end
  
  def create
    @kanri = Kanri.new(
     ka_id: params[:kanri][:ka_id],
     password: params[:kanri][:password],
     password_confirmation: params[:kanri][:password_confirmation])
     flash[:touroku] = "管理者を登録しました。"
    if @kanri.save
      redirect_to tops_ka_login_path
    else
      render 'new'
    end
  end

 def destroy 
  Kanri.find(params[:id]).destroy
  session.delete(:ka_login_uid)
    redirect_to kanris_path
    flash[:sakuzyo] = "管理者を削除しました。"
 end 
end

app/helpers/kanris_helper.rb
module KanrisHelper
end

app/views/kanris/index.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7">管理者一覧</font></p>
  　<%= link_to '講義一覧に戻る', tops_main_path,class: "btn btn-mini btn-danger" %>
  <hr color="block" >
</div>
<p><%= flash[:touroku] %></p>
<p><%= flash[:sakuzyo] %></p>

<table border="1"class="ss">

	<tr>
		<th>ID</th>
		<th>パスワード</th>
		<th>操作</th>
	</tr>

<% @kanris.each do |e| %>
	<tr>
		<td><%= e.ka_id %></td>
		<td><%= e.password %></td>
		<td>
			<%if current_user2.id == e.id %>
			<%= link_to '削除', kanri_path(e), method: :delete, data: { confirm: '削除していいですか？' } %>
			<% end %>
		</td>
	</tr>
<% end %>

</table>

app/views/kanris/new.html.erb
<div class="header" %>
  <p><font size="7">管理者登録</font></p>
  　<%= link_to 'ログイン画面に戻る', tops_ka_login_path,class: "btn btn-mini btn-danger" %>
  <hr color="block" >
</div>
  <p>一度更新してください</p>
  
<% if @kanri.errors.present? %>
<h3>エラーがあります</h3>
<ul>
	<% @kanri.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
	<% end %>
</ul>
<% end %>

<%= form_for @kanri do |f| %>

<table>
	<tr>
		<td><%= f.label :ka_id, 'ID' %></td>
		<td><%= f.text_field :ka_id %></td>
</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
		<td><p></td>
	</tr>
	<tr>
			<td><%= f.label :password, 'パスワード' %></td>
		<td><%= f.password_field :password %></td>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><%= f.label :password_confirmation, 'パスワード（確認）' %></td>
		<td><%= f.password_field :password_confirmation %></td>
		</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
		<td><p></p></td>
	</tr>
	<tr>
	</tr>
	<tr>
		<td><p></p></td>
		<td colspan="2"><%= f.submit '登録' %></td>
	</tr>
</table>

<% end %>