config/routes.rb
Rails.application.routes.draw do
  resources :kanris, only: [:create, :destroy,:edit,:view,:index,:new]
  get  'tops/main'
  root 'tops#main'
  get 'tops/st_login'
  post 'tops/st_login'
  get 'tops/friend'
  post 'tops/friend'
  get  'tops/st_logout'
  get 'tops/ka_login'
  post 'tops/ka_login'
  get  'tops/ka_logout'
  post 'subjects/:id/edit' => 'subjects#edit'
  get 'students/search'
  post 'students/search'
    get 'students/itiran'
  post 'students/itiran'
  resources :subjects, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :students, only: [:index, :new, :create, :destroy,:update,:edit]
  resources :items, only: [:index,:show,:new,:create,:destroy]
  resources :schedules, only: [:index,:show,:create]
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :schedule
  belongs_to :subject
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  @items = Item.all
  end
  
  def new
   @subjects = Subject.all
   @item = Item.new
  end

def create
      @item = Item.new(
    student_id: current_user.id,
    subject_id: params[:subject_id],
    kamoku: params[:kamoku], 
    professor: params[:professor],
    unit: params[:unit],
    youbi: params[:youbi],
    zigen: params[:zigen]
    )
    @item.save
     redirect_to new_item_path
end

def show
  @items = Item.all
end

def destroy
    Item.find(params[:id]).destroy
    redirect_to item_path
end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<div class="header" %>
  <p><font size="7"><%= current_user.st_name %>さんの時間割</font></p>
　　<%= link_to 'メインメニューに戻る', tops_st_logout_path ,class: "btn btn-mini btn-danger"%>
  <hr color="back" >
</div>
  </head>
<table border="1" class="ss">

	<tr>
		<th>subject.id</th>
		<th>student.id</th>
		<th>科目</th>
		<th>教授名</th>
		<th>単位数</th>
		<th>曜日</th>
		<th>時限</th>
	</tr>
	<% sum1 = 0%>
<% @items.each do |e|%>
<% sum = 0%>
<% p = Subject.find(e.subject_id) %>
<% if current_user.id == e.student_id %>
<tr>
	<td><%= e.subject_id %></td>
	<td><%= e.student_id %></td>
		<td><%= p.kamoku %></td>
		<td><%= p.professor %></td>
		<td><%= p.unit %></td>
		<td><%= p.youbi %></td>
		<td><%= p.zigen %></td>
</tr>
<% total = p.unit %> 
<% sum1 = sum1 + sum + total %> 
<% end %>
<% end %>
</table>
<div class="size">
	  合計<%= sum1 %>単位
</div>

app/views/items/new.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">
<head>
<div class="header" %>
  <p><font size="7"><%= current_user.st_name %>の時間割</font></p>
  
  <p>　
	<%= link_to 'トップメニューへ', root_path ,class: "btn btn-mini btn-danger"%>
</p>

</div>
<hr>
</head>
<br>
<br>
<br>
<br>
<br>
<table border="1"class="ss">
	<tr>
		<th>科目</th>
		<th>教授名</th>
		<th>単位数</th>
		<th>曜日</th>
		<th>時限</th>
		<th>登録</th>
	</tr>
 <% @subjects.each do |p| %>
	<tr>
		<td><%= p.kamoku %></td>
		<td><%= p.professor %></td>
		<td><%= p.unit %></td>
		<td><%= p.youbi %></td>
		<td><%= p.zigen %></td>
		<%= form_tag items_path(subject_id: p.id) do %>
		<td><%= submit_tag "受講する" %></td>
	</tr>
    <% end %>
<% end %>	
</table>

app/views/items/show.html.erb
    <meta charset="utf-8" />
    <link rel="stylesheet" href="tops.css" type="text/css">

<head>
<div class="header" %>
  <p><font size="7"><%= current_user.st_name %>の時間割</font></p>
  
  <p>　
	<%= link_to 'トップへ', root_path,class: "btn btn-mini btn-danger"%>
</p>

</div>
<hr>
</head>
<body>
<table border="1"class="ss">

	<tr>
		<th>科目</th>
		<th>教授名</th>
		<th>単位数</th>
		<th>曜日</th>
		<th>時限</th>
		<th>操作</th>
	</tr>
	<% sum1 = 0%>
<% @items.each do |e|%>
<% sum = 0%>
<% p = Subject.find(e.subject_id) %> 
<% if current_user.id == e.student_id %>
<tr>
		<td><%= p.kamoku %></td>
		<td><%= p.professor %></td>
		<td><%= p.unit %></td>
		<td><%= p.youbi %></td>
		<td><%= p.zigen %></td>
		<td>
			<%= link_to '削除', item_path(e), method: :delete, data: { confirm: '削除していいですか？' } %>
　　　　</td>
</tr>
<% total = p.unit %> 
<% sum1 = sum1 + sum + total %> 
<% end %>
<% end %>
</table>
<div class="size">
	  合計<%=  sum1 %>単位
</div>
</body>